import { GitHubClient } from "./github";
import { log } from "./utils";

interface PublisherConfig {
  githubOwner: string;
  githubToken: string;
  appBaseUrl: string;
}

interface PublishResult {
  success: boolean;
  commitSha?: string;
  publishedUrl?: string;
  error?: string;
}

export class Publisher {
  private github: GitHubClient;
  private config: PublisherConfig;

  constructor(config: PublisherConfig) {
    this.config = config;
    this.github = new GitHubClient(config.githubToken, config.githubOwner);
  }

  async publishArticle(
    repoName: string,
    domain: string,
    slug: string,
    title: string,
    content: string
  ): Promise<PublishResult> {
    try {
      // Detect the content directory structure in the repo
      const contentPath = await this.detectContentPath(repoName, slug);

      log.info(`Publishing to ${repoName}/${contentPath}`);

      // Commit the file via GitHub API
      const result = await this.github.createOrUpdateFile(
        repoName,
        contentPath,
        content,
        `feat: add "${title}" — auto-generated by ANKR Engine`
      );

      const commitSha = result?.content?.sha ?? result?.commit?.sha ?? null;
      const publishedUrl = `https://${domain}/${slug}`;

      log.info(
        `Published: ${publishedUrl} (commit: ${commitSha?.slice(0, 7) ?? "unknown"})`
      );

      return {
        success: true,
        commitSha,
        publishedUrl,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log.error(`Publish failed for ${slug} in ${repoName}: ${msg}`);
      return {
        success: false,
        error: msg,
      };
    }
  }

  private async detectContentPath(
    repoName: string,
    slug: string
  ): Promise<string> {
    // Try common content directory patterns
    const patterns = [
      `content/blog/${slug}.mdx`,
      `src/content/blog/${slug}.mdx`,
      `src/content/${slug}.mdx`,
      `content/${slug}.mdx`,
      `posts/${slug}.mdx`,
      `src/posts/${slug}.mdx`,
    ];

    // Check which directory exists in the repo
    for (const pattern of patterns) {
      const dir = pattern.substring(0, pattern.lastIndexOf("/"));
      try {
        await this.github.getFileContent(repoName, dir);
        return pattern;
      } catch {
        // Directory doesn't exist, try next
      }
    }

    // Default to content/blog/ — will be created by GitHub API
    return `content/blog/${slug}.mdx`;
  }

  async updateJobAfterPublish(
    jobId: string,
    result: PublishResult
  ): Promise<void> {
    const data: Record<string, unknown> = result.success
      ? {
          status: "published",
          commit_sha: result.commitSha,
          published_url: result.publishedUrl,
          published_at: new Date().toISOString(),
        }
      : {
          status: "failed",
          error_message: result.error,
        };

    try {
      await fetch(`${this.config.appBaseUrl}/api/content/${jobId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
    } catch (err) {
      log.warn(`Failed to update job ${jobId} after publish: ${err}`);
    }
  }
}
